### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by joemerlino** [robhh/SmartStatus#2]
Hi!
I just noticed that your jailbroken app has this methods inside HelperFunctions:

```
-(int)getBatteryLevel;
-(int)batteryLevel;
-(void)setBatteryLevel:(int)fp8;
```

Just wanna know if they are related to the phone's battery or pebble's battery.
Thanks!

**Comment by robhh** [comment]
That’s for the phone’s battery.

**Comment by joemerlino** [comment]
Thank you!
